-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:69
--
{-# LANGUAGE OverloadedStrings #-}
-- | This module exports HTML combinators used to create documents.
--
module Text.Blaze.Html5
    ( module Text.Blaze
    , Html
    , toHtml

    , a
    , abbr
    , address
    , area
    , article
    , aside
    , audio
    , b
    , base
    , bdo
    , blockquote
    , body
    , br
    , button
    , canvas
    , caption
    , cite
    , code
    , col
    , colgroup
    , command
    , datalist
    , dd
    , del
    , details
    , dfn
    , div
    , dl
    , dt
    , em
    , embed
    , fieldset
    , figcaption
    , figure
    , footer
    , form
    , h1
    , h2
    , h3
    , h4
    , h5
    , h6
    , head
    , header
    , hgroup
    , hr
    , html
    , i
    , iframe
    , img
    , input
    , ins
    , kbd
    , keygen
    , label
    , legend
    , li
    , link
    , map
    , mark
    , menu
    , menuitem
    , meta
    , meter
    , nav
    , noscript
    , object
    , ol
    , optgroup
    , option
    , output
    , p
    , param
    , pre
    , progress
    , q
    , rp
    , rt
    , ruby
    , samp
    , script
    , section
    , select
    , small
    , source
    , span
    , strong
    , style
    , sub
    , summary
    , sup
    , svg
    , table
    , tbody
    , td
    , textarea
    , tfoot
    , th
    , thead
    , time
    , title
    , tr
    , track
    , ul
    , var
    , video
    , wbr
    ) where

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:77
--
import Prelude (Bool(..))

import Text.Blaze
import Text.Blaze.Internal
import Text.Blaze.Svg (Svg)

type Html ev = Markup ev

toHtml :: ToMarkup a => a -> Html ev
toHtml = toMarkup


-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<a>@ element.
--
-- Example:
--
-- > a $ span $ toHtml "foo"
--
-- Result:
--
-- > <a><span>foo</span></a>
--
a :: Html ev  -- ^ Inner HTML.
  -> Html ev  -- ^ Resulting HTML.
a = Parent "a" 
{-# INLINE a #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<abbr>@ element.
--
-- Example:
--
-- > abbr $ span $ toHtml "foo"
--
-- Result:
--
-- > <abbr><span>foo</span></abbr>
--
abbr :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
abbr = Parent "abbr" 
{-# INLINE abbr #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<address>@ element.
--
-- Example:
--
-- > address $ span $ toHtml "foo"
--
-- Result:
--
-- > <address><span>foo</span></address>
--
address :: Html ev  -- ^ Inner HTML.
        -> Html ev  -- ^ Resulting HTML.
address = Parent "address" 
{-# INLINE address #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<area />@ element.
--
-- Example:
--
-- > area
--
-- Result:
--
-- > <area />
--
area :: Html ev  -- ^ Resulting HTML.
area = Leaf "area"  False
{-# INLINE area #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<article>@ element.
--
-- Example:
--
-- > article $ span $ toHtml "foo"
--
-- Result:
--
-- > <article><span>foo</span></article>
--
article :: Html ev  -- ^ Inner HTML.
        -> Html ev  -- ^ Resulting HTML.
article = Parent "article" 
{-# INLINE article #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<aside>@ element.
--
-- Example:
--
-- > aside $ span $ toHtml "foo"
--
-- Result:
--
-- > <aside><span>foo</span></aside>
--
aside :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
aside = Parent "aside" 
{-# INLINE aside #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<audio>@ element.
--
-- Example:
--
-- > audio $ span $ toHtml "foo"
--
-- Result:
--
-- > <audio><span>foo</span></audio>
--
audio :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
audio = Parent "audio" 
{-# INLINE audio #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<b>@ element.
--
-- Example:
--
-- > b $ span $ toHtml "foo"
--
-- Result:
--
-- > <b><span>foo</span></b>
--
b :: Html ev  -- ^ Inner HTML.
  -> Html ev  -- ^ Resulting HTML.
b = Parent "b" 
{-# INLINE b #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<base />@ element.
--
-- Example:
--
-- > base
--
-- Result:
--
-- > <base />
--
base :: Html ev  -- ^ Resulting HTML.
base = Leaf "base"  False
{-# INLINE base #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<bdo>@ element.
--
-- Example:
--
-- > bdo $ span $ toHtml "foo"
--
-- Result:
--
-- > <bdo><span>foo</span></bdo>
--
bdo :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
bdo = Parent "bdo" 
{-# INLINE bdo #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<blockquote>@ element.
--
-- Example:
--
-- > blockquote $ span $ toHtml "foo"
--
-- Result:
--
-- > <blockquote><span>foo</span></blockquote>
--
blockquote :: Html ev  -- ^ Inner HTML.
           -> Html ev  -- ^ Resulting HTML.
blockquote = Parent "blockquote" 
{-# INLINE blockquote #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<body>@ element.
--
-- Example:
--
-- > body $ span $ toHtml "foo"
--
-- Result:
--
-- > <body><span>foo</span></body>
--
body :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
body = Parent "body" 
{-# INLINE body #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<br />@ element.
--
-- Example:
--
-- > br
--
-- Result:
--
-- > <br />
--
br :: Html ev  -- ^ Resulting HTML.
br = Leaf "br"  False
{-# INLINE br #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<button>@ element.
--
-- Example:
--
-- > button $ span $ toHtml "foo"
--
-- Result:
--
-- > <button><span>foo</span></button>
--
button :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
button = Parent "button" 
{-# INLINE button #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<canvas>@ element.
--
-- Example:
--
-- > canvas $ span $ toHtml "foo"
--
-- Result:
--
-- > <canvas><span>foo</span></canvas>
--
canvas :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
canvas = Parent "canvas" 
{-# INLINE canvas #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<caption>@ element.
--
-- Example:
--
-- > caption $ span $ toHtml "foo"
--
-- Result:
--
-- > <caption><span>foo</span></caption>
--
caption :: Html ev  -- ^ Inner HTML.
        -> Html ev  -- ^ Resulting HTML.
caption = Parent "caption" 
{-# INLINE caption #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<cite>@ element.
--
-- Example:
--
-- > cite $ span $ toHtml "foo"
--
-- Result:
--
-- > <cite><span>foo</span></cite>
--
cite :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
cite = Parent "cite" 
{-# INLINE cite #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<code>@ element.
--
-- Example:
--
-- > code $ span $ toHtml "foo"
--
-- Result:
--
-- > <code><span>foo</span></code>
--
code :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
code = Parent "code" 
{-# INLINE code #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<col />@ element.
--
-- Example:
--
-- > col
--
-- Result:
--
-- > <col />
--
col :: Html ev  -- ^ Resulting HTML.
col = Leaf "col"  False
{-# INLINE col #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<colgroup>@ element.
--
-- Example:
--
-- > colgroup $ span $ toHtml "foo"
--
-- Result:
--
-- > <colgroup><span>foo</span></colgroup>
--
colgroup :: Html ev  -- ^ Inner HTML.
         -> Html ev  -- ^ Resulting HTML.
colgroup = Parent "colgroup" 
{-# INLINE colgroup #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<command>@ element.
--
-- Example:
--
-- > command $ span $ toHtml "foo"
--
-- Result:
--
-- > <command><span>foo</span></command>
--
command :: Html ev  -- ^ Inner HTML.
        -> Html ev  -- ^ Resulting HTML.
command = Parent "command" 
{-# INLINE command #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<datalist>@ element.
--
-- Example:
--
-- > datalist $ span $ toHtml "foo"
--
-- Result:
--
-- > <datalist><span>foo</span></datalist>
--
datalist :: Html ev  -- ^ Inner HTML.
         -> Html ev  -- ^ Resulting HTML.
datalist = Parent "datalist" 
{-# INLINE datalist #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<dd>@ element.
--
-- Example:
--
-- > dd $ span $ toHtml "foo"
--
-- Result:
--
-- > <dd><span>foo</span></dd>
--
dd :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
dd = Parent "dd" 
{-# INLINE dd #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<del>@ element.
--
-- Example:
--
-- > del $ span $ toHtml "foo"
--
-- Result:
--
-- > <del><span>foo</span></del>
--
del :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
del = Parent "del" 
{-# INLINE del #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<details>@ element.
--
-- Example:
--
-- > details $ span $ toHtml "foo"
--
-- Result:
--
-- > <details><span>foo</span></details>
--
details :: Html ev  -- ^ Inner HTML.
        -> Html ev  -- ^ Resulting HTML.
details = Parent "details" 
{-# INLINE details #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<dfn>@ element.
--
-- Example:
--
-- > dfn $ span $ toHtml "foo"
--
-- Result:
--
-- > <dfn><span>foo</span></dfn>
--
dfn :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
dfn = Parent "dfn" 
{-# INLINE dfn #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<div>@ element.
--
-- Example:
--
-- > div $ span $ toHtml "foo"
--
-- Result:
--
-- > <div><span>foo</span></div>
--
div :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
div = Parent "div" 
{-# INLINE div #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<dl>@ element.
--
-- Example:
--
-- > dl $ span $ toHtml "foo"
--
-- Result:
--
-- > <dl><span>foo</span></dl>
--
dl :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
dl = Parent "dl" 
{-# INLINE dl #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<dt>@ element.
--
-- Example:
--
-- > dt $ span $ toHtml "foo"
--
-- Result:
--
-- > <dt><span>foo</span></dt>
--
dt :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
dt = Parent "dt" 
{-# INLINE dt #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<em>@ element.
--
-- Example:
--
-- > em $ span $ toHtml "foo"
--
-- Result:
--
-- > <em><span>foo</span></em>
--
em :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
em = Parent "em" 
{-# INLINE em #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<embed />@ element.
--
-- Example:
--
-- > embed
--
-- Result:
--
-- > <embed />
--
embed :: Html ev  -- ^ Resulting HTML.
embed = Leaf "embed"  False
{-# INLINE embed #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<fieldset>@ element.
--
-- Example:
--
-- > fieldset $ span $ toHtml "foo"
--
-- Result:
--
-- > <fieldset><span>foo</span></fieldset>
--
fieldset :: Html ev  -- ^ Inner HTML.
         -> Html ev  -- ^ Resulting HTML.
fieldset = Parent "fieldset" 
{-# INLINE fieldset #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<figcaption>@ element.
--
-- Example:
--
-- > figcaption $ span $ toHtml "foo"
--
-- Result:
--
-- > <figcaption><span>foo</span></figcaption>
--
figcaption :: Html ev  -- ^ Inner HTML.
           -> Html ev  -- ^ Resulting HTML.
figcaption = Parent "figcaption" 
{-# INLINE figcaption #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<figure>@ element.
--
-- Example:
--
-- > figure $ span $ toHtml "foo"
--
-- Result:
--
-- > <figure><span>foo</span></figure>
--
figure :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
figure = Parent "figure" 
{-# INLINE figure #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<footer>@ element.
--
-- Example:
--
-- > footer $ span $ toHtml "foo"
--
-- Result:
--
-- > <footer><span>foo</span></footer>
--
footer :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
footer = Parent "footer" 
{-# INLINE footer #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<form>@ element.
--
-- Example:
--
-- > form $ span $ toHtml "foo"
--
-- Result:
--
-- > <form><span>foo</span></form>
--
form :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
form = Parent "form" 
{-# INLINE form #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<h1>@ element.
--
-- Example:
--
-- > h1 $ span $ toHtml "foo"
--
-- Result:
--
-- > <h1><span>foo</span></h1>
--
h1 :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
h1 = Parent "h1" 
{-# INLINE h1 #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<h2>@ element.
--
-- Example:
--
-- > h2 $ span $ toHtml "foo"
--
-- Result:
--
-- > <h2><span>foo</span></h2>
--
h2 :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
h2 = Parent "h2" 
{-# INLINE h2 #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<h3>@ element.
--
-- Example:
--
-- > h3 $ span $ toHtml "foo"
--
-- Result:
--
-- > <h3><span>foo</span></h3>
--
h3 :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
h3 = Parent "h3" 
{-# INLINE h3 #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<h4>@ element.
--
-- Example:
--
-- > h4 $ span $ toHtml "foo"
--
-- Result:
--
-- > <h4><span>foo</span></h4>
--
h4 :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
h4 = Parent "h4" 
{-# INLINE h4 #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<h5>@ element.
--
-- Example:
--
-- > h5 $ span $ toHtml "foo"
--
-- Result:
--
-- > <h5><span>foo</span></h5>
--
h5 :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
h5 = Parent "h5" 
{-# INLINE h5 #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<h6>@ element.
--
-- Example:
--
-- > h6 $ span $ toHtml "foo"
--
-- Result:
--
-- > <h6><span>foo</span></h6>
--
h6 :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
h6 = Parent "h6" 
{-# INLINE h6 #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<head>@ element.
--
-- Example:
--
-- > head $ span $ toHtml "foo"
--
-- Result:
--
-- > <head><span>foo</span></head>
--
head :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
head = Parent "head" 
{-# INLINE head #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<header>@ element.
--
-- Example:
--
-- > header $ span $ toHtml "foo"
--
-- Result:
--
-- > <header><span>foo</span></header>
--
header :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
header = Parent "header" 
{-# INLINE header #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<hgroup>@ element.
--
-- Example:
--
-- > hgroup $ span $ toHtml "foo"
--
-- Result:
--
-- > <hgroup><span>foo</span></hgroup>
--
hgroup :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
hgroup = Parent "hgroup" 
{-# INLINE hgroup #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<hr />@ element.
--
-- Example:
--
-- > hr
--
-- Result:
--
-- > <hr />
--
hr :: Html ev  -- ^ Resulting HTML.
hr = Leaf "hr"  False
{-# INLINE hr #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<html>@ element.
--
-- Example:
--
-- > html $ span $ toHtml "foo"
--
-- Result:
--
-- > <html><span>foo</span></html>
--
html :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
html = Parent "html" 
{-# INLINE html #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<i>@ element.
--
-- Example:
--
-- > i $ span $ toHtml "foo"
--
-- Result:
--
-- > <i><span>foo</span></i>
--
i :: Html ev  -- ^ Inner HTML.
  -> Html ev  -- ^ Resulting HTML.
i = Parent "i" 
{-# INLINE i #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<iframe>@ element.
--
-- Example:
--
-- > iframe $ span $ toHtml "foo"
--
-- Result:
--
-- > <iframe><span>foo</span></iframe>
--
iframe :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
iframe = Parent "iframe" 
{-# INLINE iframe #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<img />@ element.
--
-- Example:
--
-- > img
--
-- Result:
--
-- > <img />
--
img :: Html ev  -- ^ Resulting HTML.
img = Leaf "img"  False
{-# INLINE img #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<input />@ element.
--
-- Example:
--
-- > input
--
-- Result:
--
-- > <input />
--
input :: Html ev  -- ^ Resulting HTML.
input = Leaf "input"  False
{-# INLINE input #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<ins>@ element.
--
-- Example:
--
-- > ins $ span $ toHtml "foo"
--
-- Result:
--
-- > <ins><span>foo</span></ins>
--
ins :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
ins = Parent "ins" 
{-# INLINE ins #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<kbd>@ element.
--
-- Example:
--
-- > kbd $ span $ toHtml "foo"
--
-- Result:
--
-- > <kbd><span>foo</span></kbd>
--
kbd :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
kbd = Parent "kbd" 
{-# INLINE kbd #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<keygen />@ element.
--
-- Example:
--
-- > keygen
--
-- Result:
--
-- > <keygen />
--
keygen :: Html ev  -- ^ Resulting HTML.
keygen = Leaf "keygen"  False
{-# INLINE keygen #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<label>@ element.
--
-- Example:
--
-- > label $ span $ toHtml "foo"
--
-- Result:
--
-- > <label><span>foo</span></label>
--
label :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
label = Parent "label" 
{-# INLINE label #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<legend>@ element.
--
-- Example:
--
-- > legend $ span $ toHtml "foo"
--
-- Result:
--
-- > <legend><span>foo</span></legend>
--
legend :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
legend = Parent "legend" 
{-# INLINE legend #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<li>@ element.
--
-- Example:
--
-- > li $ span $ toHtml "foo"
--
-- Result:
--
-- > <li><span>foo</span></li>
--
li :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
li = Parent "li" 
{-# INLINE li #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<link />@ element.
--
-- Example:
--
-- > link
--
-- Result:
--
-- > <link />
--
link :: Html ev  -- ^ Resulting HTML.
link = Leaf "link"  False
{-# INLINE link #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<map>@ element.
--
-- Example:
--
-- > map $ span $ toHtml "foo"
--
-- Result:
--
-- > <map><span>foo</span></map>
--
map :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
map = Parent "map" 
{-# INLINE map #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<mark>@ element.
--
-- Example:
--
-- > mark $ span $ toHtml "foo"
--
-- Result:
--
-- > <mark><span>foo</span></mark>
--
mark :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
mark = Parent "mark" 
{-# INLINE mark #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<menu>@ element.
--
-- Example:
--
-- > menu $ span $ toHtml "foo"
--
-- Result:
--
-- > <menu><span>foo</span></menu>
--
menu :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
menu = Parent "menu" 
{-# INLINE menu #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<menuitem />@ element.
--
-- Example:
--
-- > menuitem
--
-- Result:
--
-- > <menuitem />
--
menuitem :: Html ev  -- ^ Resulting HTML.
menuitem = Leaf "menuitem"  False
{-# INLINE menuitem #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<meta />@ element.
--
-- Example:
--
-- > meta
--
-- Result:
--
-- > <meta />
--
meta :: Html ev  -- ^ Resulting HTML.
meta = Leaf "meta"  False
{-# INLINE meta #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<meter>@ element.
--
-- Example:
--
-- > meter $ span $ toHtml "foo"
--
-- Result:
--
-- > <meter><span>foo</span></meter>
--
meter :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
meter = Parent "meter" 
{-# INLINE meter #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<nav>@ element.
--
-- Example:
--
-- > nav $ span $ toHtml "foo"
--
-- Result:
--
-- > <nav><span>foo</span></nav>
--
nav :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
nav = Parent "nav" 
{-# INLINE nav #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<noscript>@ element.
--
-- Example:
--
-- > noscript $ span $ toHtml "foo"
--
-- Result:
--
-- > <noscript><span>foo</span></noscript>
--
noscript :: Html ev  -- ^ Inner HTML.
         -> Html ev  -- ^ Resulting HTML.
noscript = Parent "noscript" 
{-# INLINE noscript #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<object>@ element.
--
-- Example:
--
-- > object $ span $ toHtml "foo"
--
-- Result:
--
-- > <object><span>foo</span></object>
--
object :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
object = Parent "object" 
{-# INLINE object #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<ol>@ element.
--
-- Example:
--
-- > ol $ span $ toHtml "foo"
--
-- Result:
--
-- > <ol><span>foo</span></ol>
--
ol :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
ol = Parent "ol" 
{-# INLINE ol #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<optgroup>@ element.
--
-- Example:
--
-- > optgroup $ span $ toHtml "foo"
--
-- Result:
--
-- > <optgroup><span>foo</span></optgroup>
--
optgroup :: Html ev  -- ^ Inner HTML.
         -> Html ev  -- ^ Resulting HTML.
optgroup = Parent "optgroup" 
{-# INLINE optgroup #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<option>@ element.
--
-- Example:
--
-- > option $ span $ toHtml "foo"
--
-- Result:
--
-- > <option><span>foo</span></option>
--
option :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
option = Parent "option" 
{-# INLINE option #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<output>@ element.
--
-- Example:
--
-- > output $ span $ toHtml "foo"
--
-- Result:
--
-- > <output><span>foo</span></output>
--
output :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
output = Parent "output" 
{-# INLINE output #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<p>@ element.
--
-- Example:
--
-- > p $ span $ toHtml "foo"
--
-- Result:
--
-- > <p><span>foo</span></p>
--
p :: Html ev  -- ^ Inner HTML.
  -> Html ev  -- ^ Resulting HTML.
p = Parent "p" 
{-# INLINE p #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<param />@ element.
--
-- Example:
--
-- > param
--
-- Result:
--
-- > <param />
--
param :: Html ev  -- ^ Resulting HTML.
param = Leaf "param"  False
{-# INLINE param #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<pre>@ element.
--
-- Example:
--
-- > pre $ span $ toHtml "foo"
--
-- Result:
--
-- > <pre><span>foo</span></pre>
--
pre :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
pre = Parent "pre" 
{-# INLINE pre #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<progress>@ element.
--
-- Example:
--
-- > progress $ span $ toHtml "foo"
--
-- Result:
--
-- > <progress><span>foo</span></progress>
--
progress :: Html ev  -- ^ Inner HTML.
         -> Html ev  -- ^ Resulting HTML.
progress = Parent "progress" 
{-# INLINE progress #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<q>@ element.
--
-- Example:
--
-- > q $ span $ toHtml "foo"
--
-- Result:
--
-- > <q><span>foo</span></q>
--
q :: Html ev  -- ^ Inner HTML.
  -> Html ev  -- ^ Resulting HTML.
q = Parent "q" 
{-# INLINE q #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<rp>@ element.
--
-- Example:
--
-- > rp $ span $ toHtml "foo"
--
-- Result:
--
-- > <rp><span>foo</span></rp>
--
rp :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
rp = Parent "rp" 
{-# INLINE rp #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<rt>@ element.
--
-- Example:
--
-- > rt $ span $ toHtml "foo"
--
-- Result:
--
-- > <rt><span>foo</span></rt>
--
rt :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
rt = Parent "rt" 
{-# INLINE rt #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<ruby>@ element.
--
-- Example:
--
-- > ruby $ span $ toHtml "foo"
--
-- Result:
--
-- > <ruby><span>foo</span></ruby>
--
ruby :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
ruby = Parent "ruby" 
{-# INLINE ruby #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<samp>@ element.
--
-- Example:
--
-- > samp $ span $ toHtml "foo"
--
-- Result:
--
-- > <samp><span>foo</span></samp>
--
samp :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
samp = Parent "samp" 
{-# INLINE samp #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<script>@ element.
--
-- Example:
--
-- > script $ span $ toHtml "foo"
--
-- Result:
--
-- > <script><span>foo</span></script>
--
script :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
script = Parent "script" 
{-# INLINE script #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<section>@ element.
--
-- Example:
--
-- > section $ span $ toHtml "foo"
--
-- Result:
--
-- > <section><span>foo</span></section>
--
section :: Html ev  -- ^ Inner HTML.
        -> Html ev  -- ^ Resulting HTML.
section = Parent "section" 
{-# INLINE section #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<select>@ element.
--
-- Example:
--
-- > select $ span $ toHtml "foo"
--
-- Result:
--
-- > <select><span>foo</span></select>
--
select :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
select = Parent "select" 
{-# INLINE select #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<small>@ element.
--
-- Example:
--
-- > small $ span $ toHtml "foo"
--
-- Result:
--
-- > <small><span>foo</span></small>
--
small :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
small = Parent "small" 
{-# INLINE small #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<source />@ element.
--
-- Example:
--
-- > source
--
-- Result:
--
-- > <source />
--
source :: Html ev  -- ^ Resulting HTML.
source = Leaf "source"  False
{-# INLINE source #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<span>@ element.
--
-- Example:
--
-- > span $ span $ toHtml "foo"
--
-- Result:
--
-- > <span><span>foo</span></span>
--
span :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
span = Parent "span" 
{-# INLINE span #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<strong>@ element.
--
-- Example:
--
-- > strong $ span $ toHtml "foo"
--
-- Result:
--
-- > <strong><span>foo</span></strong>
--
strong :: Html ev  -- ^ Inner HTML.
       -> Html ev  -- ^ Resulting HTML.
strong = Parent "strong" 
{-# INLINE strong #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<style>@ element.
--
-- Example:
--
-- > style $ span $ toHtml "foo"
--
-- Result:
--
-- > <style><span>foo</span></style>
--
style :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
style = Parent "style" 
{-# INLINE style #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<sub>@ element.
--
-- Example:
--
-- > sub $ span $ toHtml "foo"
--
-- Result:
--
-- > <sub><span>foo</span></sub>
--
sub :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
sub = Parent "sub" 
{-# INLINE sub #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<summary>@ element.
--
-- Example:
--
-- > summary $ span $ toHtml "foo"
--
-- Result:
--
-- > <summary><span>foo</span></summary>
--
summary :: Html ev  -- ^ Inner HTML.
        -> Html ev  -- ^ Resulting HTML.
summary = Parent "summary" 
{-# INLINE summary #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<sup>@ element.
--
-- Example:
--
-- > sup $ span $ toHtml "foo"
--
-- Result:
--
-- > <sup><span>foo</span></sup>
--
sup :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
sup = Parent "sup" 
{-# INLINE sup #-}

-- | Combinator for the @\<svg>@ element.
--
-- Example:
--
-- > svg ! width "100" ! height "100" $
-- >   circle ! cx "50" ! cy "50" ! r "40"
--
-- Result:
--
-- > <svg width="100" height="100"><circle cx="50" cy="50" r="40"/></svg>
--
svg :: Svg ev -> Html ev
svg = Parent "svg" 
{-# INLINE svg #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<table>@ element.
--
-- Example:
--
-- > table $ span $ toHtml "foo"
--
-- Result:
--
-- > <table><span>foo</span></table>
--
table :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
table = Parent "table" 
{-# INLINE table #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<tbody>@ element.
--
-- Example:
--
-- > tbody $ span $ toHtml "foo"
--
-- Result:
--
-- > <tbody><span>foo</span></tbody>
--
tbody :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
tbody = Parent "tbody" 
{-# INLINE tbody #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<td>@ element.
--
-- Example:
--
-- > td $ span $ toHtml "foo"
--
-- Result:
--
-- > <td><span>foo</span></td>
--
td :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
td = Parent "td" 
{-# INLINE td #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<textarea>@ element.
--
-- Example:
--
-- > textarea $ span $ toHtml "foo"
--
-- Result:
--
-- > <textarea><span>foo</span></textarea>
--
-- NOTE: In ReactJS, <textarea> elements shouldn't have children.
textarea :: Html ev  -- ^ Resulting HTML.
textarea = Leaf "textarea"  False
{-# INLINE textarea #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<tfoot>@ element.
--
-- Example:
--
-- > tfoot $ span $ toHtml "foo"
--
-- Result:
--
-- > <tfoot><span>foo</span></tfoot>
--
tfoot :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
tfoot = Parent "tfoot" 
{-# INLINE tfoot #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<th>@ element.
--
-- Example:
--
-- > th $ span $ toHtml "foo"
--
-- Result:
--
-- > <th><span>foo</span></th>
--
th :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
th = Parent "th" 
{-# INLINE th #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<thead>@ element.
--
-- Example:
--
-- > thead $ span $ toHtml "foo"
--
-- Result:
--
-- > <thead><span>foo</span></thead>
--
thead :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
thead = Parent "thead" 
{-# INLINE thead #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<time>@ element.
--
-- Example:
--
-- > time $ span $ toHtml "foo"
--
-- Result:
--
-- > <time><span>foo</span></time>
--
time :: Html ev  -- ^ Inner HTML.
     -> Html ev  -- ^ Resulting HTML.
time = Parent "time" 
{-# INLINE time #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<title>@ element.
--
-- Example:
--
-- > title $ span $ toHtml "foo"
--
-- Result:
--
-- > <title><span>foo</span></title>
--
title :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
title = Parent "title" 
{-# INLINE title #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<tr>@ element.
--
-- Example:
--
-- > tr $ span $ toHtml "foo"
--
-- Result:
--
-- > <tr><span>foo</span></tr>
--
tr :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
tr = Parent "tr" 
{-# INLINE tr #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<track />@ element.
--
-- Example:
--
-- > track
--
-- Result:
--
-- > <track />
--
track :: Html ev  -- ^ Resulting HTML.
track = Leaf "track"  False
{-# INLINE track #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<ul>@ element.
--
-- Example:
--
-- > ul $ span $ toHtml "foo"
--
-- Result:
--
-- > <ul><span>foo</span></ul>
--
ul :: Html ev  -- ^ Inner HTML.
   -> Html ev  -- ^ Resulting HTML.
ul = Parent "ul" 
{-# INLINE ul #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<var>@ element.
--
-- Example:
--
-- > var $ span $ toHtml "foo"
--
-- Result:
--
-- > <var><span>foo</span></var>
--
var :: Html ev  -- ^ Inner HTML.
    -> Html ev  -- ^ Resulting HTML.
var = Parent "var" 
{-# INLINE var #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:199
--
-- | Combinator for the @\<video>@ element.
--
-- Example:
--
-- > video $ span $ toHtml "foo"
--
-- Result:
--
-- > <video><span>foo</span></video>
--
video :: Html ev  -- ^ Inner HTML.
      -> Html ev  -- ^ Resulting HTML.
video = Parent "video" 
{-# INLINE video #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:226
--
-- | Combinator for the @\<wbr />@ element.
--
-- Example:
--
-- > wbr
--
-- Result:
--
-- > <wbr />
--
wbr :: Html ev  -- ^ Resulting HTML.
wbr = Leaf "wbr"  False
{-# INLINE wbr #-}
