-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:93
--
-- | This module exports combinators that provide you with the
-- ability to set attributes on HTML elements.
--
{-# LANGUAGE OverloadedStrings #-}
module Text.Blaze.Html5.Attributes
    ( accept
    , accesskey
    , action
    , allowfullscreen
    , allowtransparency
    , alt
    , async
    , autocapitalize
    , autocomplete
    , autocorrect
    , autofocus
    , autoplay
    , cellpadding
    , cellspacing
    , charset
    , checked
    , class_
    , colspan
    , cols
    , content
    , contenteditable
    , contextmenu
    , controls
    , coords
    , crossorigin
    , data_
    , datetime
    , defer
    , dir
    , disabled
    , download
    , draggable
    , enctype
    , form
    , formnovalidate
    , frameborder
    , height
    , hidden
    , href
    , hreflang
    , for
    , httpequiv
    , icon
    , id
    , itemprop
    , itemscope
    , itemtype
    , key
    , label
    , lang
    , list
    , loop
    , max
    , maxlength
    , mediagroup
    , method
    , min
    , multiple
    , muted
    , name
    , novalidate
    , pattern
    , placeholder
    , poster
    , preload
    , property
    , radiogroup
    , readonly
    , rel
    , required
    , role
    , rowspan
    , rows
    , sandbox
    , scope
    , scrollleft
    , scrolltop
    , scrolling
    , seamless
    , selected
    , shape
    , size
    , span
    , spellcheck
    , src
    , srcdoc
    , srcset
    , start
    , step
    , style
    , tabindex
    , target
    , title
    , type_
    , usemap
    , value
    , width
    , wmode
    ) where

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:99
--
import Prelude (Bool)

import qualified Data.Text           as T
import qualified Data.HashMap.Strict as HMS

import Text.Blaze.Internal ( Attribute, AttributeValue, attribute
                           , boolAttribute, objectAttribute
                           )

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @accept@ attribute.
--
-- Example:
--
-- > div ! accept "bar" $ "Hello."
--
-- Result:
--
-- > <div accept="bar">Hello.</div>
--
accept :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
accept = attribute "accept"
{-# INLINE accept #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @accessKey@ attribute.
--
-- Example:
--
-- > div ! accesskey "bar" $ "Hello."
--
-- Result:
--
-- > <div accessKey="bar">Hello.</div>
--
accesskey :: AttributeValue  -- ^ Attribute value.
          -> Attribute ev    -- ^ Resulting attribute.
accesskey = attribute "accessKey"
{-# INLINE accesskey #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @action@ attribute.
--
-- Example:
--
-- > div ! action "bar" $ "Hello."
--
-- Result:
--
-- > <div action="bar">Hello.</div>
--
action :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
action = attribute "action"
{-# INLINE action #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @allowFullScreen@ attribute.
--
-- Example:
--
-- > div ! allowfullscreen "bar" $ "Hello."
--
-- Result:
--
-- > <div allowFullScreen="bar">Hello.</div>
--
allowfullscreen :: AttributeValue  -- ^ Attribute value.
                -> Attribute ev    -- ^ Resulting attribute.
allowfullscreen = attribute "allowFullScreen"
{-# INLINE allowfullscreen #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @allowTransparency@ attribute.
--
-- Example:
--
-- > div ! allowtransparency "bar" $ "Hello."
--
-- Result:
--
-- > <div allowTransparency="bar">Hello.</div>
--
allowtransparency :: AttributeValue  -- ^ Attribute value.
                  -> Attribute ev    -- ^ Resulting attribute.
allowtransparency = attribute "allowTransparency"
{-# INLINE allowtransparency #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @alt@ attribute.
--
-- Example:
--
-- > div ! alt "bar" $ "Hello."
--
-- Result:
--
-- > <div alt="bar">Hello.</div>
--
alt :: AttributeValue  -- ^ Attribute value.
    -> Attribute ev    -- ^ Resulting attribute.
alt = attribute "alt"
{-# INLINE alt #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @async@ attribute.
--
-- Example:
--
-- > div ! async "bar" $ "Hello."
--
-- Result:
--
-- > <div async="bar">Hello.</div>
--
async :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
async = attribute "async"
{-# INLINE async #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @autoCapitalize@ attribute.
--
-- Example:
--
-- > div ! autocapitalize "bar" $ "Hello."
--
-- Result:
--
-- > <div autoCapitalize="bar">Hello.</div>
--
autocapitalize :: AttributeValue  -- ^ Attribute value.
               -> Attribute ev    -- ^ Resulting attribute.
autocapitalize = attribute "autoCapitalize"
{-# INLINE autocapitalize #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @autoComplete@ attribute.
--
-- Example:
--
-- > div ! autocomplete "bar" $ "Hello."
--
-- Result:
--
-- > <div autoComplete="bar">Hello.</div>
--
autocomplete :: AttributeValue  -- ^ Attribute value.
             -> Attribute ev    -- ^ Resulting attribute.
autocomplete = attribute "autoComplete"
{-# INLINE autocomplete #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @autoCorrect@ attribute.
--
-- Example:
--
-- > div ! autocorrect "bar" $ "Hello."
--
-- Result:
--
-- > <div autoCorrect="bar">Hello.</div>
--
autocorrect :: AttributeValue  -- ^ Attribute value.
            -> Attribute ev    -- ^ Resulting attribute.
autocorrect = attribute "autoCorrect"
{-# INLINE autocorrect #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @autoFocus@ attribute.
--
-- Example:
--
-- > div ! autofocus "bar" $ "Hello."
--
-- Result:
--
-- > <div autoFocus="bar">Hello.</div>
--
autofocus :: Bool            -- ^ Attribute value.
          -> Attribute ev    -- ^ Resulting attribute.
autofocus = boolAttribute "autoFocus"
{-# INLINE autofocus #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @autoPlay@ attribute.
--
-- Example:
--
-- > div ! autoplay "bar" $ "Hello."
--
-- Result:
--
-- > <div autoPlay="bar">Hello.</div>
--
autoplay :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
autoplay = attribute "autoPlay"
{-# INLINE autoplay #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @cellPadding@ attribute.
--
-- Example:
--
-- > div ! cellpadding "bar" $ "Hello."
--
-- Result:
--
-- > <div cellPadding="bar">Hello.</div>
--
cellpadding :: AttributeValue  -- ^ Attribute value.
            -> Attribute ev    -- ^ Resulting attribute.
cellpadding = attribute "cellPadding"
{-# INLINE cellpadding #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @cellSpacing@ attribute.
--
-- Example:
--
-- > div ! cellspacing "bar" $ "Hello."
--
-- Result:
--
-- > <div cellSpacing="bar">Hello.</div>
--
cellspacing :: AttributeValue  -- ^ Attribute value.
            -> Attribute ev    -- ^ Resulting attribute.
cellspacing = attribute "cellSpacing"
{-# INLINE cellspacing #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @charSet@ attribute.
--
-- Example:
--
-- > div ! charset "bar" $ "Hello."
--
-- Result:
--
-- > <div charSet="bar">Hello.</div>
--
charset :: AttributeValue  -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
charset = attribute "charSet"
{-# INLINE charset #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @checked@ attribute.
--
-- Example:
--
-- > div ! checked "bar" $ "Hello."
--
-- Result:
--
-- > <div checked="bar">Hello.</div>
--
checked :: Bool            -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
checked = boolAttribute "checked"
{-# INLINE checked #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @className@ attribute.
--
-- Example:
--
-- > div ! class_ "bar" $ "Hello."
--
-- Result:
--
-- > <div className="bar">Hello.</div>
--
class_ :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
class_ = attribute "className"
{-# INLINE class_ #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @colSpan@ attribute.
--
-- Example:
--
-- > div ! colspan "bar" $ "Hello."
--
-- Result:
--
-- > <div colSpan="bar">Hello.</div>
--
colspan :: AttributeValue  -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
colspan = attribute "colSpan"
{-# INLINE colspan #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @cols@ attribute.
--
-- Example:
--
-- > div ! cols "bar" $ "Hello."
--
-- Result:
--
-- > <div cols="bar">Hello.</div>
--
cols :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
cols = attribute "cols"
{-# INLINE cols #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @content@ attribute.
--
-- Example:
--
-- > div ! content "bar" $ "Hello."
--
-- Result:
--
-- > <div content="bar">Hello.</div>
--
content :: AttributeValue  -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
content = attribute "content"
{-# INLINE content #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @contentEditable@ attribute.
--
-- Example:
--
-- > div ! contenteditable "bar" $ "Hello."
--
-- Result:
--
-- > <div contentEditable="bar">Hello.</div>
--
contenteditable :: AttributeValue  -- ^ Attribute value.
                -> Attribute ev    -- ^ Resulting attribute.
contenteditable = attribute "contentEditable"
{-# INLINE contenteditable #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @contextMenu@ attribute.
--
-- Example:
--
-- > div ! contextmenu "bar" $ "Hello."
--
-- Result:
--
-- > <div contextMenu="bar">Hello.</div>
--
contextmenu :: AttributeValue  -- ^ Attribute value.
            -> Attribute ev    -- ^ Resulting attribute.
contextmenu = attribute "contextMenu"
{-# INLINE contextmenu #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @controls@ attribute.
--
-- Example:
--
-- > div ! controls "bar" $ "Hello."
--
-- Result:
--
-- > <div controls="bar">Hello.</div>
--
controls :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
controls = attribute "controls"
{-# INLINE controls #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @coords@ attribute.
--
-- Example:
--
-- > div ! coords "bar" $ "Hello."
--
-- Result:
--
-- > <div coords="bar">Hello.</div>
--
coords :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
coords = attribute "coords"
{-# INLINE coords #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @crossOrigin@ attribute.
--
-- Example:
--
-- > div ! crossorigin "bar" $ "Hello."
--
-- Result:
--
-- > <div crossOrigin="bar">Hello.</div>
--
crossorigin :: AttributeValue  -- ^ Attribute value.
            -> Attribute ev    -- ^ Resulting attribute.
crossorigin = attribute "crossOrigin"
{-# INLINE crossorigin #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @data@ attribute.
--
-- Example:
--
-- > div ! data_ "bar" $ "Hello."
--
-- Result:
--
-- > <div data="bar">Hello.</div>
--
data_ :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
data_ = attribute "data"
{-# INLINE data_ #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @dateTime@ attribute.
--
-- Example:
--
-- > div ! datetime "bar" $ "Hello."
--
-- Result:
--
-- > <div dateTime="bar">Hello.</div>
--
datetime :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
datetime = attribute "dateTime"
{-# INLINE datetime #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @defer@ attribute.
--
-- Example:
--
-- > div ! defer "bar" $ "Hello."
--
-- Result:
--
-- > <div defer="bar">Hello.</div>
--
defer :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
defer = attribute "defer"
{-# INLINE defer #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @dir@ attribute.
--
-- Example:
--
-- > div ! dir "bar" $ "Hello."
--
-- Result:
--
-- > <div dir="bar">Hello.</div>
--
dir :: AttributeValue  -- ^ Attribute value.
    -> Attribute ev    -- ^ Resulting attribute.
dir = attribute "dir"
{-# INLINE dir #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @disabled@ attribute.
--
-- Example:
--
-- > div ! disabled "bar" $ "Hello."
--
-- Result:
--
-- > <div disabled="bar">Hello.</div>
--
disabled :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
disabled = attribute "disabled"
{-# INLINE disabled #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @download@ attribute.
--
-- Example:
--
-- > div ! download "bar" $ "Hello."
--
-- Result:
--
-- > <div download="bar">Hello.</div>
--
download :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
download = attribute "download"
{-# INLINE download #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @draggable@ attribute.
--
-- Example:
--
-- > div ! draggable "bar" $ "Hello."
--
-- Result:
--
-- > <div draggable="bar">Hello.</div>
--
draggable :: AttributeValue  -- ^ Attribute value.
          -> Attribute ev    -- ^ Resulting attribute.
draggable = attribute "draggable"
{-# INLINE draggable #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @encType@ attribute.
--
-- Example:
--
-- > div ! enctype "bar" $ "Hello."
--
-- Result:
--
-- > <div encType="bar">Hello.</div>
--
enctype :: AttributeValue  -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
enctype = attribute "encType"
{-# INLINE enctype #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @form@ attribute.
--
-- Example:
--
-- > div ! form "bar" $ "Hello."
--
-- Result:
--
-- > <div form="bar">Hello.</div>
--
form :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
form = attribute "form"
{-# INLINE form #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @formNoValidate@ attribute.
--
-- Example:
--
-- > div ! formnovalidate "bar" $ "Hello."
--
-- Result:
--
-- > <div formNoValidate="bar">Hello.</div>
--
formnovalidate :: AttributeValue  -- ^ Attribute value.
               -> Attribute ev    -- ^ Resulting attribute.
formnovalidate = attribute "formNoValidate"
{-# INLINE formnovalidate #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @frameBorder@ attribute.
--
-- Example:
--
-- > div ! frameborder "bar" $ "Hello."
--
-- Result:
--
-- > <div frameBorder="bar">Hello.</div>
--
frameborder :: AttributeValue  -- ^ Attribute value.
            -> Attribute ev    -- ^ Resulting attribute.
frameborder = attribute "frameBorder"
{-# INLINE frameborder #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @height@ attribute.
--
-- Example:
--
-- > div ! height "bar" $ "Hello."
--
-- Result:
--
-- > <div height="bar">Hello.</div>
--
height :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
height = attribute "height"
{-# INLINE height #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @hidden@ attribute.
--
-- Example:
--
-- > div ! hidden "bar" $ "Hello."
--
-- Result:
--
-- > <div hidden="bar">Hello.</div>
--
hidden :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
hidden = attribute "hidden"
{-# INLINE hidden #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @href@ attribute.
--
-- Example:
--
-- > div ! href "bar" $ "Hello."
--
-- Result:
--
-- > <div href="bar">Hello.</div>
--
href :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
href = attribute "href"
{-# INLINE href #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @hrefLang@ attribute.
--
-- Example:
--
-- > div ! hreflang "bar" $ "Hello."
--
-- Result:
--
-- > <div hrefLang="bar">Hello.</div>
--
hreflang :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
hreflang = attribute "hrefLang"
{-# INLINE hreflang #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @htmlFor@ attribute.
--
-- Example:
--
-- > div ! for "bar" $ "Hello."
--
-- Result:
--
-- > <div htmlFor="bar">Hello.</div>
--
for :: AttributeValue  -- ^ Attribute value.
    -> Attribute ev    -- ^ Resulting attribute.
for = attribute "htmlFor"
{-# INLINE for #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @httpEquiv@ attribute.
--
-- Example:
--
-- > div ! httpequiv "bar" $ "Hello."
--
-- Result:
--
-- > <div httpEquiv="bar">Hello.</div>
--
httpequiv :: AttributeValue  -- ^ Attribute value.
          -> Attribute ev    -- ^ Resulting attribute.
httpequiv = attribute "httpEquiv"
{-# INLINE httpequiv #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @icon@ attribute.
--
-- Example:
--
-- > div ! icon "bar" $ "Hello."
--
-- Result:
--
-- > <div icon="bar">Hello.</div>
--
icon :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
icon = attribute "icon"
{-# INLINE icon #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @id@ attribute.
--
-- Example:
--
-- > div ! id "bar" $ "Hello."
--
-- Result:
--
-- > <div id="bar">Hello.</div>
--
id :: AttributeValue  -- ^ Attribute value.
   -> Attribute ev    -- ^ Resulting attribute.
id = attribute "id"
{-# INLINE id #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @itemProp@ attribute.
--
-- Example:
--
-- > div ! itemprop "bar" $ "Hello."
--
-- Result:
--
-- > <div itemProp="bar">Hello.</div>
--
itemprop :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
itemprop = attribute "itemProp"
{-# INLINE itemprop #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @itemScope@ attribute.
--
-- Example:
--
-- > div ! itemscope "bar" $ "Hello."
--
-- Result:
--
-- > <div itemScope="bar">Hello.</div>
--
itemscope :: AttributeValue  -- ^ Attribute value.
          -> Attribute ev    -- ^ Resulting attribute.
itemscope = attribute "itemScope"
{-# INLINE itemscope #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @itemType@ attribute.
--
-- Example:
--
-- > div ! itemtype "bar" $ "Hello."
--
-- Result:
--
-- > <div itemType="bar">Hello.</div>
--
itemtype :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
itemtype = attribute "itemType"
{-# INLINE itemtype #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @key@ attribute.
--
-- Example:
--
-- > div ! key "bar" $ "Hello."
--
-- Result:
--
-- > <div key="bar">Hello.</div>
--
key :: AttributeValue  -- ^ Attribute value.
    -> Attribute ev    -- ^ Resulting attribute.
key = attribute "key"
{-# INLINE key #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @label@ attribute.
--
-- Example:
--
-- > div ! label "bar" $ "Hello."
--
-- Result:
--
-- > <div label="bar">Hello.</div>
--
label :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
label = attribute "label"
{-# INLINE label #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @lang@ attribute.
--
-- Example:
--
-- > div ! lang "bar" $ "Hello."
--
-- Result:
--
-- > <div lang="bar">Hello.</div>
--
lang :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
lang = attribute "lang"
{-# INLINE lang #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @list@ attribute.
--
-- Example:
--
-- > div ! list "bar" $ "Hello."
--
-- Result:
--
-- > <div list="bar">Hello.</div>
--
list :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
list = attribute "list"
{-# INLINE list #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @loop@ attribute.
--
-- Example:
--
-- > div ! loop "bar" $ "Hello."
--
-- Result:
--
-- > <div loop="bar">Hello.</div>
--
loop :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
loop = attribute "loop"
{-# INLINE loop #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @max@ attribute.
--
-- Example:
--
-- > div ! max "bar" $ "Hello."
--
-- Result:
--
-- > <div max="bar">Hello.</div>
--
max :: AttributeValue  -- ^ Attribute value.
    -> Attribute ev    -- ^ Resulting attribute.
max = attribute "max"
{-# INLINE max #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @maxLength@ attribute.
--
-- Example:
--
-- > div ! maxlength "bar" $ "Hello."
--
-- Result:
--
-- > <div maxLength="bar">Hello.</div>
--
maxlength :: AttributeValue  -- ^ Attribute value.
          -> Attribute ev    -- ^ Resulting attribute.
maxlength = attribute "maxLength"
{-# INLINE maxlength #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @mediaGroup@ attribute.
--
-- Example:
--
-- > div ! mediagroup "bar" $ "Hello."
--
-- Result:
--
-- > <div mediaGroup="bar">Hello.</div>
--
mediagroup :: AttributeValue  -- ^ Attribute value.
           -> Attribute ev    -- ^ Resulting attribute.
mediagroup = attribute "mediaGroup"
{-# INLINE mediagroup #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @method@ attribute.
--
-- Example:
--
-- > div ! method "bar" $ "Hello."
--
-- Result:
--
-- > <div method="bar">Hello.</div>
--
method :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
method = attribute "method"
{-# INLINE method #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @min@ attribute.
--
-- Example:
--
-- > div ! min "bar" $ "Hello."
--
-- Result:
--
-- > <div min="bar">Hello.</div>
--
min :: AttributeValue  -- ^ Attribute value.
    -> Attribute ev    -- ^ Resulting attribute.
min = attribute "min"
{-# INLINE min #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @multiple@ attribute.
--
-- Example:
--
-- > div ! multiple "bar" $ "Hello."
--
-- Result:
--
-- > <div multiple="bar">Hello.</div>
--
multiple :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
multiple = attribute "multiple"
{-# INLINE multiple #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @muted@ attribute.
--
-- Example:
--
-- > div ! muted "bar" $ "Hello."
--
-- Result:
--
-- > <div muted="bar">Hello.</div>
--
muted :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
muted = attribute "muted"
{-# INLINE muted #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @name@ attribute.
--
-- Example:
--
-- > div ! name "bar" $ "Hello."
--
-- Result:
--
-- > <div name="bar">Hello.</div>
--
name :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
name = attribute "name"
{-# INLINE name #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @noValidate@ attribute.
--
-- Example:
--
-- > div ! novalidate "bar" $ "Hello."
--
-- Result:
--
-- > <div noValidate="bar">Hello.</div>
--
novalidate :: AttributeValue  -- ^ Attribute value.
           -> Attribute ev    -- ^ Resulting attribute.
novalidate = attribute "noValidate"
{-# INLINE novalidate #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @pattern@ attribute.
--
-- Example:
--
-- > div ! pattern "bar" $ "Hello."
--
-- Result:
--
-- > <div pattern="bar">Hello.</div>
--
pattern :: AttributeValue  -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
pattern = attribute "pattern"
{-# INLINE pattern #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @placeholder@ attribute.
--
-- Example:
--
-- > div ! placeholder "bar" $ "Hello."
--
-- Result:
--
-- > <div placeholder="bar">Hello.</div>
--
placeholder :: AttributeValue  -- ^ Attribute value.
            -> Attribute ev    -- ^ Resulting attribute.
placeholder = attribute "placeholder"
{-# INLINE placeholder #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @poster@ attribute.
--
-- Example:
--
-- > div ! poster "bar" $ "Hello."
--
-- Result:
--
-- > <div poster="bar">Hello.</div>
--
poster :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
poster = attribute "poster"
{-# INLINE poster #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @preload@ attribute.
--
-- Example:
--
-- > div ! preload "bar" $ "Hello."
--
-- Result:
--
-- > <div preload="bar">Hello.</div>
--
preload :: AttributeValue  -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
preload = attribute "preload"
{-# INLINE preload #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @property@ attribute.
--
-- Example:
--
-- > div ! property "bar" $ "Hello."
--
-- Result:
--
-- > <div property="bar">Hello.</div>
--
property :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
property = attribute "property"
{-# INLINE property #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @radioGroup@ attribute.
--
-- Example:
--
-- > div ! radiogroup "bar" $ "Hello."
--
-- Result:
--
-- > <div radioGroup="bar">Hello.</div>
--
radiogroup :: AttributeValue  -- ^ Attribute value.
           -> Attribute ev    -- ^ Resulting attribute.
radiogroup = attribute "radioGroup"
{-# INLINE radiogroup #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @readOnly@ attribute.
--
-- Example:
--
-- > div ! readonly "bar" $ "Hello."
--
-- Result:
--
-- > <div readOnly="bar">Hello.</div>
--
readonly :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
readonly = attribute "readOnly"
{-# INLINE readonly #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @rel@ attribute.
--
-- Example:
--
-- > div ! rel "bar" $ "Hello."
--
-- Result:
--
-- > <div rel="bar">Hello.</div>
--
rel :: AttributeValue  -- ^ Attribute value.
    -> Attribute ev    -- ^ Resulting attribute.
rel = attribute "rel"
{-# INLINE rel #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @required@ attribute.
--
-- Example:
--
-- > div ! required "bar" $ "Hello."
--
-- Result:
--
-- > <div required="bar">Hello.</div>
--
required :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
required = attribute "required"
{-# INLINE required #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @role@ attribute.
--
-- Example:
--
-- > div ! role "bar" $ "Hello."
--
-- Result:
--
-- > <div role="bar">Hello.</div>
--
role :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
role = attribute "role"
{-# INLINE role #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @rowSpan@ attribute.
--
-- Example:
--
-- > div ! rowspan "bar" $ "Hello."
--
-- Result:
--
-- > <div rowSpan="bar">Hello.</div>
--
rowspan :: AttributeValue  -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
rowspan = attribute "rowSpan"
{-# INLINE rowspan #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @rows@ attribute.
--
-- Example:
--
-- > div ! rows "bar" $ "Hello."
--
-- Result:
--
-- > <div rows="bar">Hello.</div>
--
rows :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
rows = attribute "rows"
{-# INLINE rows #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @sandbox@ attribute.
--
-- Example:
--
-- > div ! sandbox "bar" $ "Hello."
--
-- Result:
--
-- > <div sandbox="bar">Hello.</div>
--
sandbox :: AttributeValue  -- ^ Attribute value.
        -> Attribute ev    -- ^ Resulting attribute.
sandbox = attribute "sandbox"
{-# INLINE sandbox #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @scope@ attribute.
--
-- Example:
--
-- > div ! scope "bar" $ "Hello."
--
-- Result:
--
-- > <div scope="bar">Hello.</div>
--
scope :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
scope = attribute "scope"
{-# INLINE scope #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @scrollLeft@ attribute.
--
-- Example:
--
-- > div ! scrollleft "bar" $ "Hello."
--
-- Result:
--
-- > <div scrollLeft="bar">Hello.</div>
--
scrollleft :: AttributeValue  -- ^ Attribute value.
           -> Attribute ev    -- ^ Resulting attribute.
scrollleft = attribute "scrollLeft"
{-# INLINE scrollleft #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @scrollTop@ attribute.
--
-- Example:
--
-- > div ! scrolltop "bar" $ "Hello."
--
-- Result:
--
-- > <div scrollTop="bar">Hello.</div>
--
scrolltop :: AttributeValue  -- ^ Attribute value.
          -> Attribute ev    -- ^ Resulting attribute.
scrolltop = attribute "scrollTop"
{-# INLINE scrolltop #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @scrolling@ attribute.
--
-- Example:
--
-- > div ! scrolling "bar" $ "Hello."
--
-- Result:
--
-- > <div scrolling="bar">Hello.</div>
--
scrolling :: AttributeValue  -- ^ Attribute value.
          -> Attribute ev    -- ^ Resulting attribute.
scrolling = attribute "scrolling"
{-# INLINE scrolling #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @seamless@ attribute.
--
-- Example:
--
-- > div ! seamless "bar" $ "Hello."
--
-- Result:
--
-- > <div seamless="bar">Hello.</div>
--
seamless :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
seamless = attribute "seamless"
{-# INLINE seamless #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @selected@ attribute.
--
-- Example:
--
-- > div ! selected "bar" $ "Hello."
--
-- Result:
--
-- > <div selected="bar">Hello.</div>
--
selected :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
selected = attribute "selected"
{-# INLINE selected #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @shape@ attribute.
--
-- Example:
--
-- > div ! shape "bar" $ "Hello."
--
-- Result:
--
-- > <div shape="bar">Hello.</div>
--
shape :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
shape = attribute "shape"
{-# INLINE shape #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @size@ attribute.
--
-- Example:
--
-- > div ! size "bar" $ "Hello."
--
-- Result:
--
-- > <div size="bar">Hello.</div>
--
size :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
size = attribute "size"
{-# INLINE size #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @span@ attribute.
--
-- Example:
--
-- > div ! span "bar" $ "Hello."
--
-- Result:
--
-- > <div span="bar">Hello.</div>
--
span :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
span = attribute "span"
{-# INLINE span #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @spellCheck@ attribute.
--
-- Example:
--
-- > div ! spellcheck "bar" $ "Hello."
--
-- Result:
--
-- > <div spellCheck="bar">Hello.</div>
--
spellcheck :: AttributeValue  -- ^ Attribute value.
           -> Attribute ev    -- ^ Resulting attribute.
spellcheck = attribute "spellCheck"
{-# INLINE spellcheck #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @src@ attribute.
--
-- Example:
--
-- > div ! src "bar" $ "Hello."
--
-- Result:
--
-- > <div src="bar">Hello.</div>
--
src :: AttributeValue  -- ^ Attribute value.
    -> Attribute ev    -- ^ Resulting attribute.
src = attribute "src"
{-# INLINE src #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @srcDoc@ attribute.
--
-- Example:
--
-- > div ! srcdoc "bar" $ "Hello."
--
-- Result:
--
-- > <div srcDoc="bar">Hello.</div>
--
srcdoc :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
srcdoc = attribute "srcDoc"
{-# INLINE srcdoc #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @srcSet@ attribute.
--
-- Example:
--
-- > div ! srcset "bar" $ "Hello."
--
-- Result:
--
-- > <div srcSet="bar">Hello.</div>
--
srcset :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
srcset = attribute "srcSet"
{-# INLINE srcset #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @start@ attribute.
--
-- Example:
--
-- > div ! start "bar" $ "Hello."
--
-- Result:
--
-- > <div start="bar">Hello.</div>
--
start :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
start = attribute "start"
{-# INLINE start #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @step@ attribute.
--
-- Example:
--
-- > div ! step "bar" $ "Hello."
--
-- Result:
--
-- > <div step="bar">Hello.</div>
--
step :: AttributeValue  -- ^ Attribute value.
     -> Attribute ev    -- ^ Resulting attribute.
step = attribute "step"
{-# INLINE step #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @style@ attribute.

-- TODO (basvandijk): Add an example to the documentation.
style :: HMS.HashMap T.Text T.Text  -- ^ Attribute value.
      -> Attribute ev               -- ^ Resulting attribute.
style = objectAttribute "style"
{-# INLINE style #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @tabIndex@ attribute.
--
-- Example:
--
-- > div ! tabindex "bar" $ "Hello."
--
-- Result:
--
-- > <div tabIndex="bar">Hello.</div>
--
tabindex :: AttributeValue  -- ^ Attribute value.
         -> Attribute ev    -- ^ Resulting attribute.
tabindex = attribute "tabIndex"
{-# INLINE tabindex #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @target@ attribute.
--
-- Example:
--
-- > div ! target "bar" $ "Hello."
--
-- Result:
--
-- > <div target="bar">Hello.</div>
--
target :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
target = attribute "target"
{-# INLINE target #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @title@ attribute.
--
-- Example:
--
-- > div ! title "bar" $ "Hello."
--
-- Result:
--
-- > <div title="bar">Hello.</div>
--
title :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
title = attribute "title"
{-# INLINE title #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @type@ attribute.
--
-- Example:
--
-- > div ! type_ "bar" $ "Hello."
--
-- Result:
--
-- > <div type="bar">Hello.</div>
--
type_ :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
type_ = attribute "type"
{-# INLINE type_ #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @useMap@ attribute.
--
-- Example:
--
-- > div ! usemap "bar" $ "Hello."
--
-- Result:
--
-- > <div useMap="bar">Hello.</div>
--
usemap :: AttributeValue  -- ^ Attribute value.
       -> Attribute ev    -- ^ Resulting attribute.
usemap = attribute "useMap"
{-# INLINE usemap #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @value@ attribute.
--
-- Example:
--
-- > div ! value "bar" $ "Hello."
--
-- Result:
--
-- > <div value="bar">Hello.</div>
--
value :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
value = attribute "value"
{-# INLINE value #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @width@ attribute.
--
-- Example:
--
-- > div ! width "bar" $ "Hello."
--
-- Result:
--
-- > <div width="bar">Hello.</div>
--
width :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
width = attribute "width"
{-# INLINE width #-}

-- WARNING: The next block of code was automatically generated by
-- src/Util/GenerateHtmlCombinators.hs:249
--
-- | Combinator for the @wmode@ attribute.
--
-- Example:
--
-- > div ! wmode "bar" $ "Hello."
--
-- Result:
--
-- > <div wmode="bar">Hello.</div>
--
wmode :: AttributeValue  -- ^ Attribute value.
      -> Attribute ev    -- ^ Resulting attribute.
wmode = attribute "wmode"
{-# INLINE wmode #-}
